<h1 align=center>Code to reduce dataset</h1>
<h3> Load libraries and dataset .csv file</h3>

In [1]:
import pandas as pd
import numpy as np

#will need to update address of UNCC_sampled.csv to local address
data = pd.read_csv("UNCC_sampled2.csv",quoting=3, error_bad_lines=False)

FileNotFoundError: File b'UNCC_sampled2.csv' does not exist

<h3>The dataset</h3>

In [22]:
#displays data
data.head()

,SubmitPerView,Ratio,Customer Value Score,SubmissionScore2,Submission Score,Credit Card Apply Clicked (ev69) (event69),Date,Express No Offers (ev13) (event13),Express Visited (ev290) (event290),FCS Client Signup Completed (ev73) (event73),...,MyLT Session Started (ev189) (event189),Number of Records,Page Views,Product Reporting,TreeAuthID (evar50),Visit Number,Visitor ID,cchannel (eVar19) (evar19),csource (eVar20) (evar20),Qformuid (Evar1)
0,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,0,1,1,NaN,NaN,1,7732198244151778867_4134450918576237336,content,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,0,1,1,Refinance,NaN,4,2431284746265101166_8567539867164911934,display,NaN,11633f92-360a-448f-b416-755ea16b6419
2,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,0,1,1,Refinance,NaN,2,5951927093440429627_8402229250223050888,display,NaN,3786b340-e685-4798-8004-6ee5807934c3
3,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,0,1,0,Refinance,NaN,1,9095128932057308643_5744753714959771864,display,NaN,3eb4e8c0-dd45-4001-820f-0a83980472d8
4,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,0,1,1,Refinance,NaN,1,7144494725347131737_7936627049048254284,display,NaN,50aad01f-07a3-45ec-a575-65d89900168f

<h3>Dataset size and list of named columns</h3>

In [23]:
print('(rows, columns) ', data.shape)
data.columns

(rows, columns)  (2995760, 33)

Index(['SubmitPerView', 'Ratio', 'Customer Value Score', 'SubmissionScore2',
       'Submission Score', 'Credit Card Apply Clicked (ev69) (event69)',
       'Date', 'Express No Offers (ev13) (event13)',
       'Express Visited (ev290) (event290)',
       'FCS Client Signup Completed (ev73) (event73)',
       'FCS Qform Optin Completed (ev373) (event373)',
       'Form Conversion (ev59) (event59)',
       'Form Engagement 1 (ev11) (event11)',
       'Form Engagement 2 (ev12) (event12)', 'FormStart (ev57) (event57)',
       'FormSubmit in Express Offers (ev58) (event58)',
       'GeoSegmentation States (group)', 'State',
       'GeoSegmentation States - Split 2', 'GeoSegmentation States',
       'Lender Not Matched (ev522) (event522)',
       'Lenders Matched (ev501) (event501)', 'Mobile Device Type',
       'MyLT Session Started (ev189) (event189)', 'Number of Records',
       'Page Views', 'Product Reporting', 'TreeAuthID (evar50)',
       'Visit Number', 'Visitor ID', 'cchannel  (eVar19) (evar19)',
       'csource (eVar20) (evar20)', 'Qformuid (Evar1)'],
      dtype='object')

In [26]:
data.drop(columns = ['TreeAuthID (evar50)', 'GeoSegmentation States (group)', 'GeoSegmentation States - Split 2', 'GeoSegmentation States'])

,SubmitPerView,Ratio,Customer Value Score,SubmissionScore2,Submission Score,Credit Card Apply Clicked (ev69) (event69),Date,Express No Offers (ev13) (event13),Express Visited (ev290) (event290),FCS Client Signup Completed (ev73) (event73),...,Mobile Device Type,MyLT Session Started (ev189) (event189),Number of Records,Page Views,Product Reporting,Visit Number,Visitor ID,cchannel (eVar19) (evar19),csource (eVar20) (evar20),Qformuid (Evar1)
0,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Gaming Console,0,1,1,NaN,1,7732198244151778867_4134450918576237336,content,NaN,NaN
1,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Gaming Console,0,1,1,Refinance,4,2431284746265101166_8567539867164911934,display,NaN,11633f92-360a-448f-b416-755ea16b6419
2,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Gaming Console,0,1,1,Refinance,2,5951927093440429627_8402229250223050888,display,NaN,3786b340-e685-4798-8004-6ee5807934c3
3,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Gaming Console,0,1,0,Refinance,1,9095128932057308643_5744753714959771864,display,NaN,3eb4e8c0-dd45-4001-820f-0a83980472d8
4,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Gaming Console,0,1,1,Refinance,1,7144494725347131737_7936627049048254284,display,NaN,50aad01f-07a3-45ec-a575-65d89900168f
5,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Gaming Console,0,1,1,NaN,1,3840395548288420783_2563166581193760536,display,NaN,6e1c1405-ffe0-486e-9bbd-46b62efa71e0
6,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Gaming Console,0,1,1,Refinance,5,5951927093440429627_8402229250223050888,display,NaN,b2b0ad9e-1a0d-4153-88c1-db3564acf2be
7,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Media Player,0,1,13,Refinance,1,9193455551599519817_2133625214278931623,content,NaN,72650659-e1b0-4a0c-9bc0-da2152f4f0a3
8,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Media Player,0,1,1,Refinance,3,4427865552475720477_747171176657803548,display,NaN,29f06188-b6ad-415f-9565-42d9e66f7c9a
9,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Media Player,0,1,1,Refinance,1,1114696381134181432_6527712537278417460,display,NaN,5f1df36c-fbd2-4e53-aaa9-ad02563a19b1
10,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Media Player,0,1,1,Refinance,1,9117345142982298598_3577160519644552955,display,NaN,cff11909-1619-420f-80ce-bdfb8579141f
11,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Media Player,0,1,1,NaN,1,3489213251580014308_7398156064548572149,sem,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,1045083400990673712_8865219555642043783,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,104959404389931813_7664988777389669386,NaN,NaN,NaN
14,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,1,NaN,1,1187440273274509770_6264289359886443009,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,1259023831_2274431552,NaN,NaN,NaN
16,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,5,NaN,1,1422243278321408217_1794656872289764929,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,1470397279149965160_4056554722587805186,NaN,NaN,NaN
18,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,1,NaN,1,1529432820598411557_4243204992246694562,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,1709893692233310714_6128893313841640312,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,1745541608653249458_7227558626993931477,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,1861684549292256734_6435018148321770551,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,0,NaN,1,2169372723960481604_258221103072382442,NaN,NaN,NaN
23,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,1,NaN,1,2176559230035865039_6028598558958540714,NaN,NaN,NaN
24,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,2,NaN,1,2187762442256815536_577073384131518846,NaN,NaN,NaN
25,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,1,NaN,1,2208096828633599876_2524339848122002493,NaN,NaN,NaN
26,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,2,NaN,1,2385508582254797716_2877051979529532200,NaN,NaN,NaN
27,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,1,NaN,1,2390655788272990649_62550287593796688,NaN,NaN,NaN
28,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,1,NaN,1,265569730221593432_960506058289255664,NaN,NaN,NaN
29,0.0,0.0,0.0,0.0,0.0,0,1/1/2018,0,0,0,...,Mobile Phone,0,1,1,NaN,1,2666065567448156575_1758368723776643525,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995730,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,4474094593284351823_2692296758913801334,display,NaN,4b50fd3b-c645-4a58-a129-11d83b6d5a65
2995731,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,6962772376860754426_2292538529102484165,display,NaN,4c8c7b5d-95d6-4981-a02b-eeb5b7dfe189
2995732,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,4705594752857309629_8845426663376865756,display,NaN,4d7be3dd-7182-436e-98eb-e81e7064a705
2995733,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,5642076409898579287_607118805370109419,display,NaN,4e201b6c-a38b-4416-a338-e9f8ef6cf9e0
2995734,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,94586580994858256_2981541975354490542,display,NaN,4e762707-e3f6-41a0-9b2c-4020d2757dc4
2995735,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,4898147426486854620_801967259435646216,display,NaN,4f41d0ce-1711-422a-8888-72c502194c59
2995736,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,3657306861043457106_2374674021817069557,display,NaN,52b57d16-6d99-4a9f-a012-e118ea1f5057
2995737,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,6577078889595094300_6646617171334828231,display,NaN,54f8bfd1-c62e-408c-8d5c-8b4ae6b84b0d
2995738,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,7668392121780253644_8389786986646277002,display,NaN,5638f32f-6d47-4900-a812-f91455695f7b
2995739,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,3493840594125098444_4474798721974096835,display,NaN,59c9f3d0-2f54-42d4-bfa1-8b6816f9ea4e
2995740,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,5938634174441761054_630748696755628593,display,NaN,5a71a7b1-3ac7-4e33-a6d2-018a26522d64
2995741,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,5170788871887036393_4523915421172848036,display,NaN,5e4a81bd-00f8-4808-b4dc-0aca545b1641
2995742,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,5869830302664627826_8326123479595036204,display,NaN,5f777487-237d-4877-95d3-1830bb66ccec
2995743,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,3486182470403646046_7635364392254391553,display,NaN,602e9aa8-0d26-4aa3-bf6d-e5741b1532f3
2995744,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,4889213644877264911_454329563843772941,display,NaN,603eec87-ef94-4452-97ce-da71b180f813
2995745,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,6709351487657006126_2076734926070274374,display,NaN,623ed678-fa38-49dc-b2b4-3ea6ad9dd384
2995746,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,2857983042445642958_6859259181504146320,display,NaN,62666009-9734-42a8-bc14-52df5f139a9c
2995747,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,5635695921266723706_891255649032156021,display,NaN,68616282-1d2c-4f1d-b3ba-e322d0ac2f28
2995748,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,6765966537827209028_1843054862192896072,display,NaN,6953780e-395e-4811-b00a-b4fca143ea6a
2995749,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,773453771050587883_5022477692072233643,display,NaN,6a3ba5e6-e185-4e49-90b1-63707390082c
2995750,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,5394206372327083797_8845931764235465211,display,NaN,6a50b140-e8ab-476c-a249-d1e0dcbb89e6
2995751,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,3716949062545431997_1317203477764726420,display,NaN,6bf597d6-10f1-4b96-87ef-658224b9cbc3
2995752,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,2115617929781553002_4265586885985995841,display,NaN,6ce7d5fc-c00c-4510-8bda-03509a3a41a9
2995753,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,19054980805026730_8867215671009367290,display,NaN,7029a425-75be-4fcd-9f4c-cd7bae86655b
2995754,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,5131555305005162439_4347325164811312158,display,NaN,70c0bcb1-f7f0-4203-9c44-a8aae09db8c6
2995755,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,323930282969950330_4140977524605716107,display,NaN,7191ebd5-cf9c-411f-804e-14c961e0ff9f
2995756,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,6556396268369138371_6883153618751320251,display,NaN,7302d575-5a62-4b59-afe7-41c0a83f9e85
2995757,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,7510090809257532125_2849250196605017319,display,NaN,735c1b9f-4a2a-4c7d-a132-0e2ea7bfc84e
2995758,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,2265818693156584614_2467518606969255815,display,NaN,73b302db-1187-4399-9d43-a713e040f8f5
2995759,0.0,0.0,0.0,0.0,0.0,0,1/4/2018,0,0,0,...,Mobile Phone,0,1,1,Refinance,1,4529596766361655623_6619266054569731195,display,NaN,7503d828-8eb8-44dc-8006-108dfaaab203

In [27]:
data.to_csv('UNCCSampledDropped.csv', sep=',')

<h3>Add generated data to dataframe</h3>

In [15]:
#generated score added to dataframe
#data['score']=score


#data['GeoSegmentation States'].str.replace(' (united states)',"")

#data['GeoSegmentation States']

<h3>Code to extract specific columns into a new .csv file</h3>

#update this list with the column names of the data paramater to be used
columns_to_use = ['Date','Product Reporting','GeoSegmentation States','Page Views',
       'Credit Card Apply Clicked (ev69) (event69)','FormSubmit in Express Offers (ev58) (event58)',
       'MyLT Session Started (ev189) (event189)']
#new dataframe of just the sesired columns
small_data = data[columns_to_use]
#update output file name as needed
small_data.to_csv('small_UNCC.csv', sep=',')
#prints new size of data
print(small_data.shape)

<h3>Drops rows from data set that are empty in a specific set of columns</h3>

#drops rows that have Nan values(no value) in any column in the subset

data = data.dropna(subset=['SubmitPerView', 'Ratio', 'Customer Value Score', 'SubmissionScore2',
       'Submission Score', 'Credit Card Apply Clicked (ev69) (event69)',
       'Date', 'Express No Offers (ev13) (event13)',
       'Express Visited (ev290) (event290)',
       'FCS Client Signup Completed (ev73) (event73)',
       'FCS Qform Optin Completed (ev373) (event373)',
       'Form Conversion (ev59) (event59)',
       'Form Engagement 1 (ev11) (event11)',
       'Form Engagement 2 (ev12) (event12)', 'FormStart (ev57) (event57)',
       'FormSubmit in Express Offers (ev58) (event58)',
       'GeoSegmentation States (group)', 'State',
       'GeoSegmentation States - Split 2', 'GeoSegmentation States',
       'Lender Not Matched (ev522) (event522)',
       'Lenders Matched (ev501) (event501)', 'Mobile Device Type',
       'MyLT Session Started (ev189) (event189)', 'Number of Records',
       'Page Views', 'Product Reporting', 'TreeAuthID (evar50)',
       'Visit Number', 'Visitor ID', 'cchannel  (eVar19) (evar19)',
       'csource (eVar20) (evar20)', 'Qformuid (Evar1)'])
#prints the new size of the data
print(data.shape)
#update output file name as needed
data.to_csv('UNCCSampledSmall.csv', sep=',')